### ISSUE TITLE
[Question] Could it be useful to also have a visual representations of these migrations?

### ISSUE THREAD

**Issue by romanthekat** [kokizzu/list-of-tech-migrations#9]
Hi!
Could it be useful to also have a visual representations of these migrations?
Something like this (a big one):
![result](https://user-images.githubusercontent.com/6695292/150743700-2aa2554f-1d73-4955-bce9-7b6c6c9cae6e.png)

I basically converted the migrations into something consumable by [Graphviz](https://en.wikipedia.org/wiki/Graphviz), and then plotted it.

Hypothetically it can be re-generated on a commit with GitHub actions, but even manual update once in a while could possibly be useful. Or maybe not :)

What do you think?

P.S. I will also try to find a way to group vertices somehow, like per languages/databases/etc., to make it more readable, but that's for the next time

**Comment by kokizzu** [comment]
maybe just the technology will be ok, instead of company names

**Comment by romanthekat** [comment]
Something like this? :) 
![result](https://user-images.githubusercontent.com/6695292/150829129-a5cb7159-7eda-4481-81b6-dd7d99162435.png)

Looks cleaner. If it's good enough I can submit PR

**Comment by kokizzu** [comment]
very nice :3
